"""Schemas for invoking Gemini-powered agents."""
from __future__ import annotations

from pydantic import BaseModel, Field

from .snapshot import WebDocument


class GeminiAgentRequest(BaseModel):
    message: str = Field(..., description="Prompt or instruction for the Gemini agent")
    documents: list[WebDocument] | None = Field(
        default=None,
        description="Optional context documents to ground the response.",
    )


class GeminiAgentResponse(BaseModel):
    output: str = Field(..., description="Natural-language response generated by the agent")
