"""Schemas for query planning and orchestration."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class QueryTask(BaseModel):
    """Single query instruction for downstream retrieval."""

    query: str = Field(..., description="Search query string")
    intent: Literal["broad", "targeted", "trend", "risk"] = Field(
        default="targeted", description="High-level intent for this query"
    )
    priority: int = Field(
        default=1, description="Relative priority order (1=highest)"
    )
    topic: str = Field(
        default="general", description="Topic cluster for diversity tracking"
    )


class QueryPlan(BaseModel):
    """Structured plan generated by the query orchestrator."""

    strategy: str = Field(..., description="Narrative summary of the retrieval strategy")
    queries: list[QueryTask] = Field(default_factory=list, description="List of queries to execute")
    expected_results: list[str] = Field(
        default_factory=list,
        description="Hypotheses or observations the orchestrator expects to validate",
    )
